### ISSUE TITLE
Can't Build SPA App Using 'ng build --prod'

### ISSUE THREAD

**Issue by Osama94** [TryCatchLearn/DatingApp_2.2_Archive#7]
ERROR in src/app/messages/messages.component.html(28,44): This condition will always return 'false' since the types '"Unread"' and '"Outbox"' have no overlap.        
src/app/messages/messages.component.html(32,16): This condition will always return 'true' since the types '"Unread"' and '"Outbox"' have no overlap.
src/app/messages/messages.component.html(36,16): This condition will always return 'false' since the types '"Unread"' and '"Outbox"' have no overlap.

**Comment by emmanuelbitang** [comment]
If anyone is still looking for answers try declaring the variable messageContainer of type string in "messages.component.ts"  then try rebuilding.
![ngbuilderror](https://user-images.githubusercontent.com/26601000/89106074-6e8af600-d459-11ea-9a93-91fdd75d9bde.JPG)
